### ISSUE TITLE
PKG_LIBS replicated

### ISSUE THREAD

**Issue by muschellij2** [stnava/ANTsRCore#20]
## Multiple PKG_LIBS weird issues
Can someone explain to me why `libants` and why `libitk` are repeated over and over again in [`configure`](https://github.com/stnava/ANTsRCore/blob/master/configure#L63)? 
```
echo "PKG_LIBS=\${libitk} \${libants} \${libitk} \${libants} \${libitk} \
                 \${libants} \${libitk} \${libants} \${itklib} \${libants} \
                 \${libitk} \${libants} \${itklib} \${libants} \${itklib} \
                 \${libants} \${libitk} \${libants} \${itklib}" >> Makevars
```

## Reducing PKG_LIBS

 I thought it would be sufficient to replace it with `echo "PKG_LIBS=\${libitk} \${libants}"`.  That is not the case as referenced https://github.com/muschellij2/ANTsRCore/commit/6b459db9fc93096ba0a51a74edef86d634264c62 BUT BUILDS under OSX and not Linux!  Linux error was the one I've been getting:
```
Error: package or namespace load failed for ‘ANTsRCore’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/travis/build/muschellij2/ANTsRCore.Rcheck/ANTsRCore/libs/ANTsRCore.so':
  /home/travis/build/muschellij2/ANTsRCore.Rcheck/ANTsRCore/libs/ANTsRCore.so: undefined symbol: _ZTIN3itk18MetaDataObjectBaseE
```
so it wasn't different build configs that caused this I don't think but `PKG_LIBS`

## Repeating PKG_LIBS
When I switched the PKG_LIBS argument back we got Linux build, but timeout on OSX! https://travis-ci.org/muschellij2/ANTsRCore/builds/258889981, where the commit https://github.com/muschellij2/ANTsRCore/commit/54ff57ade7ab91cdcb115eecda05647fa6a8c16f indicates that's all was changed!

I think this may be the cause of some of our headaches @stnava @jeffduda with timeouts, but I don't know why this would be the case at all.  Either of you going to JSM 2017 in Baltimore?

**Comment by stnava** [comment]
it is related to this:

https://stackoverflow.com/questions/12573816/what-is-an-undefined-reference-unresolved-external-symbol-error-and-how-do-i-fix

specifically (seemingly) circular library dependencies or some suboptimal ordering that requires the libraries to be repeated to resolve symbol definitions.

this is platform dependent and compiler dependent.

it's possible that if we found the optimal ordering of libraries , we could avoid repeating the libraries in the `PKG_LIBS`.   at this time, though, i dont have another platform independent solution.

**Comment by muschellij2** [comment]
OK I get that, but I don't understand why something like:
```
echo "PKG_LIBS=\${libitk} \${libants} \${libitk} \${libants}" >> Makevars
```
wouldn't be sufficient vs:
```
echo "PKG_LIBS=\${libitk} \${libants} \${libitk} \${libants} \${libitk} \
                 \${libants} \${libitk} \${libants} \${itklib} \${libants} \
                 \${libitk} \${libants} \${itklib} \${libants} \${itklib} \
                 \${libants} \${libitk} \${libants} \${itklib}" >> Makevars
```

but it seems to make a difference.
