### ISSUE TITLE
Resampling and dropping one dimensions

### ISSUE THREAD

**Issue by muschellij2** [stnava/ANTsRCore#7]
So I have an image (resampler.nii.gz): [https://figshare.com/s/f2b7d125d98086c328e4](https://figshare.com/s/f2b7d125d98086c328e4)

Load up `ANTsRCore`
```r
rm(list = ls())
for (i in 1:5) gc()
library(ANTsRCore)
```

```
## 
## Attaching package: 'ANTsRCore'
```

```
## The following object is masked from 'package:stats':
## 
##     var
```

```
## The following objects are masked from 'package:base':
## 
##     all, any, apply, max, min, prod, range, sum
```

Simple Function for resampling back and checking the dimensions are the same as the original image:
```r
check_dim = function(
  x, 
  dims = c(512L, 512L, 471L),
  pdim = c(0.664062023162842, 0.664062023162842, 0.625)) {
  
  back = resampleImage(x, resampleParams = pdim)
  print(dim(back))
  all(dim(back) == dims)
}

img = "resampler.nii.gz"
img = antsImageRead(img)
dim(img)
```
```
## [1] 512 512 471
```
```r
dput(antsGetSpacing(img))
```
```
## c(0.664062023162842, 0.664062023162842, 0.625)
```
```r
check_dim(img)
```
```
## [1] 512 512 471
## [1] TRUE
```

Resample to 1x1x1
```r
reg_img = resampleImage(img, c(1,1,1))
check_dim(reg_img)
```

This drops a z-dimension
```
## [1] 512 512 470
## [1] FALSE
```

Confirming this happens when cloning:
```r
reg_img = antsImageClone(img)
reg_img = resampleImage(reg_img, c(1,1,1))
check_dim(reg_img)
```

```
## [1] 512 512 470
## [1] FALSE
```

I could use `resampleImageToTarget`, but I don't know if this is a bug with rounding or an undefined problem due to rounding/ceiling/flooring. 

Any thoughts?

**Comment by stnava** [comment]
i would call this a rounding issue.

you can resample using voxel dimensions rather than spacing to avoid this.

or resampleImageToTarget, as you note.

also - the physical space is preserved here, regardless of image size.


brian
